# Generated by Django 4.2.1 on 2023-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('grade', models.CharField(max_length=10)),
                ('admission_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
